// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sndbdwbjzobfygsbgwzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZGJkd2Jqem9iZnlnc2Jnd3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDMxNzAsImV4cCI6MjA2MzE3OTE3MH0.kT2D0tkFyo3rpTg9WVwoML8pwt3KLvhqpHDTFEJnSZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);